city = input('write: ')
print(city)
print("thank you")
city = input(' ')
print(city)
print("thank you")
city = input(' ')
print(city)
print("thank you")
city = input(' ')
print(city)
print("thank you")
